global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'neural_core'
    static_configs:
      - targets: ['host.docker.internal:9090', 'core:9090']
    metrics_path: /metrics
